# rosalind-iev: calculate the expected value of offspring in the next
# 		generationd displaying the dominant phenotype

APP := iev
SRC = main.c
OBJ = ${SRC:.c=.o}
EXTERN_OBJ = "../common/util.o"

include ../config.mk
include ../default.mk
include ../binary.mk
