# rosalind-hamm: calculate the hamming distance between two strings

APP = hamm
SRC = main.c
OBJ = ${SRC:.c=.o}
EXTERN_OBJ = "../common/util.o"

include ../config.mk
include ../default.mk
include ../binary.mk
