# rosalind-prot: convert RNA into Protein strings

APP := prot
SRC = main.c
OBJ = ${SRC:.c=.o}
EXTERN_OBJ = "../common/rna.o" "../common/util.o"

include ../config.mk
include ../default.mk
include ../binary.mk
